/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QueueAntri;

import static QueueAntri.MenuAntri.antrean;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Riwayat extends javax.swing.JFrame {

    /**
     * Creates new form Riwayat
     */
    private DefaultTableModel tabmode;
    
    public Riwayat() {
        initComponents();
        tampil_database();
        
        // Kustomisasi header tabel dengan border tebal
        JTableHeader header = tabel_riwayat.getTableHeader();
        header.setFont(new Font("SansSerif", Font.BOLD, 16)); // Font tebal
        header.setBackground(Color.WHITE);                   // Latar putih
        header.setForeground(Color.BLACK);                   // Teks hitam
        header.setOpaque(true);

        // Mengatur renderer untuk header dengan border
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = new JLabel(value.toString());
                label.setHorizontalAlignment(SwingConstants.CENTER);
                label.setFont(new Font("SansSerif", Font.BOLD, 16));
                label.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1)); // Border hitam
                label.setBackground(Color.WHITE);
                label.setOpaque(true);
                return label;
            }
        });

        // Kustomisasi isi tabel
        tabel_riwayat.setFont(new Font("SansSerif", Font.PLAIN, 14));
        tabel_riwayat.setRowHeight(30); // Tinggi baris
        tabel_riwayat.setGridColor(Color.BLACK); // Garis tabel hitam
    }
    
    public void tampil_database(){
        Object[] baris = {"Nama","Usia","Keluhan", "Prioritas", "Waktu Datang", "Waktu Selesai"};
        Object[][] pasienArray = new Object[RiwayatPasien.ambilRiwayat().size()][5];
        int i = 0;
        for(Pasien n : RiwayatPasien.ambilRiwayat()){
            String[] arrData = {n.getNama(), Integer.toString(n.getUsia()), n.getKeluhan(), (n.getPrioritas() == 1 ? "Darurat" : "Reguler"),
                                n.getWaktuDatang().toString(), n.getWaktuSelesai().toString()};
            pasienArray[i] = arrData;
            i++;
        }
        tabmode = new DefaultTableModel(pasienArray, baris);
        tabel_riwayat.setModel(tabmode);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_riwayat = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_data = new javax.swing.JButton();
        Gambar = new javax.swing.JLabel();
        Gambar1 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Daftar Riwayat Pasien");
        setIconImages(null);
        setLocation(new java.awt.Point(100, -5));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabel_riwayat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabel_riwayat.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tabel_riwayat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 820, 370));

        txt_cari.setFont(new java.awt.Font("Helvetica Rounded", 3, 18)); // NOI18N
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 200, 40));

        btn_cari.setFont(new java.awt.Font("Helvetica Rounded", 3, 18)); // NOI18N
        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queueantri/UI/icons8-search-36.png"))); // NOI18N
        btn_cari.setAlignmentY(0.0F);
        btn_cari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 40, 40));

        btn_data.setFont(new java.awt.Font("Helvetica Rounded", 3, 18)); // NOI18N
        btn_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queueantri/UI/icons8-reset-36 (1).png"))); // NOI18N
        btn_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 40, 40));

        Gambar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(Gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1040, -1));

        Gambar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Gambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queueantri/UI/RiwayatPasien.png"))); // NOI18N
        getContentPane().add(Gambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1040, 810));

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        MenuAntri menu = new MenuAntri();
        dispose();
        menu.tampil_data();
        menu.setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        if (txt_cari.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Kolom pencarian kosong !");
            txt_cari.requestFocus();
        } else {
            Object[] baris = {"Nama","Usia","Keluhan", "Prioritas", "Waktu Datang", "Waktu Selesai"};
            Object[][] pasienArray = new Object[RiwayatPasien.ambilRiwayat().size()][5];
            
            try {
                String cari = txt_cari.getText();
                int i = 0;
            for(Pasien n : RiwayatPasien.cariData(cari)){
                String[] arrData = {n.getNama(), Integer.toString(n.getUsia()), n.getKeluhan(), (n.getPrioritas() == 1 ? "Darurat" : "Reguler"),
                                n.getWaktuDatang().toString(), n.getWaktuSelesai().toString()};
                pasienArray[i] = arrData;
                i++;
            }
            tabmode = new DefaultTableModel(pasienArray, baris);
            tabel_riwayat.setModel(tabmode);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataActionPerformed
        tampil_database();
    }//GEN-LAST:event_btn_dataActionPerformed

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            btn_cari.doClick();
        }
    }//GEN-LAST:event_txt_cariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar;
    private javax.swing.JLabel Gambar1;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_data;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_riwayat;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
