/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QueueAntri;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class TambahAntrian extends javax.swing.JFrame {

    QueueAntriApp que = new QueueAntriApp();
    /**
     * Creates new form TambahAntrian
     */
    public TambahAntrian() {
        initComponents();
    }
    
    
    public void reset_text() {
        cb_prioritas.setSelectedItem(" ");
        txt_nama.setText("");
        txt_keluhan.setText("");
        txt_usia.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nama = new javax.swing.JTextField();
        txt_usia = new javax.swing.JTextField();
        txt_keluhan = new javax.swing.JTextField();
        cb_prioritas = new javax.swing.JComboBox<>();
        Gambar = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nama.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_nama.setBorder(null);
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 390, 30));

        txt_usia.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_usia.setBorder(null);
        getContentPane().add(txt_usia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 390, 30));

        txt_keluhan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_keluhan.setBorder(null);
        getContentPane().add(txt_keluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 412, 390, 30));

        cb_prioritas.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        cb_prioritas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Reguler", "Darurat" }));
        cb_prioritas.setBorder(null);
        cb_prioritas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cb_prioritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_prioritasActionPerformed(evt);
            }
        });
        getContentPane().add(cb_prioritas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 420, 40));

        Gambar.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        Gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queueantri/UI/AntrianPasien.png"))); // NOI18N
        getContentPane().add(Gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1060, 800));

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        btn_tambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_tambahKeyPressed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 160, 40));

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        if (txt_nama.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Nama Pasien belum diisi!");
            txt_nama.requestFocus();
        } else if (txt_usia.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Usia Pasien belum diisi!");
            txt_usia.requestFocus();
        } else if (txt_keluhan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Keluhan Pasien diisi!");
            txt_keluhan.requestFocus();
        } else if (cb_prioritas.getSelectedItem().equals(" ")){
            JOptionPane.showMessageDialog(null,"Maaf, Prioritas Pasien belum dipilih!");
            cb_prioritas.requestFocus();
        }  else {
            try{
                String nama = txt_nama.getText();
                int usia = Integer.valueOf(txt_usia.getText());
                String keluhan = txt_keluhan.getText();
                int prioritas = cb_prioritas.getSelectedItem().equals("Darurat")  ? 1 : 2;
                
                MenuAntri menu = new MenuAntri();
                menu.tambahAntri(nama, usia, keluhan, prioritas);
                JOptionPane.showMessageDialog(null, "Pasien Berhasil ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                reset_text();
                dispose();
                menu.tampil_data();
                menu.setVisible(true);
            } catch (NumberFormatException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null,"Maaf, Masukkan Usia dalam Bentuk Angka");
            }
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        MenuAntri menu = new MenuAntri();
        dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_tambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_tambahKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            btn_tambah.doClick();
        }
    }//GEN-LAST:event_btn_tambahKeyPressed

    private void cb_prioritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_prioritasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_prioritasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahAntrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_prioritas;
    private javax.swing.JTextField txt_keluhan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_usia;
    // End of variables declaration//GEN-END:variables
}
